source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, :deployment_target => '15.0'

def shared_pods
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxBluetoothKit2'
  pod "CryptoSwift"
  pod 'Swinject'
  pod "CocoaLumberjack/Swift"
end

target 'XMCommDemo' do
  project 'XMCommDemo'
  shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end